local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 
LSM:Register("background", "Bricks", [[Interface\Addons\SharedMedia_MyMedia\background\Bricks.tga]]) 
LSM:Register("background", "Brushedmetal", [[Interface\Addons\SharedMedia_MyMedia\background\Brushedmetal.tga]]) 
LSM:Register("background", "Copper", [[Interface\Addons\SharedMedia_MyMedia\background\Copper.tga]]) 
LSM:Register("background", "Moo", [[Interface\Addons\SharedMedia_MyMedia\background\Moo.tga]]) 
LSM:Register("background", "OverlayRect", [[Interface\Addons\SharedMedia_MyMedia\background\OverlayRect.tga]]) 
LSM:Register("background", "ScreenOverlay", [[Interface\Addons\SharedMedia_MyMedia\background\ScreenOverlay.tga]]) 
LSM:Register("background", "Smoke", [[Interface\Addons\SharedMedia_MyMedia\background\Smoke.tga]]) 

-- ----- 
--  BORDER 
-- ---- 
LSM:Register("border", "Ferous1", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous1.tga]]) 
LSM:Register("border", "Ferous10", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous10.tga]]) 
LSM:Register("border", "Ferous11", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous11.tga]]) 
LSM:Register("border", "Ferous12", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous12.tga]]) 
LSM:Register("border", "Ferous13", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous13.tga]]) 
LSM:Register("border", "Ferous2", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous2.tga]]) 
LSM:Register("border", "Ferous3", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous3.tga]]) 
LSM:Register("border", "Ferous4", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous4.tga]]) 
LSM:Register("border", "Ferous5", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous5.tga]]) 
LSM:Register("border", "Ferous6", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous6.tga]]) 
LSM:Register("border", "Ferous7", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous7.tga]]) 
LSM:Register("border", "Ferous8", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous8.tga]]) 
LSM:Register("border", "Ferous9", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous9.tga]]) 
LSM:Register("border", "RaeliGlow", [[Interface\Addons\SharedMedia_MyMedia\border\RaeliGlow.tga]]) 
LSM:Register("border", "RaeliGlowSmall", [[Interface\Addons\SharedMedia_MyMedia\border\RaeliGlowSmall.tga]]) 
LSM:Register("border", "RothSquare", [[Interface\Addons\SharedMedia_MyMedia\border\RothSquare.tga]]) 
LSM:Register("border", "SeerahScalloped", [[Interface\Addons\SharedMedia_MyMedia\border\SeerahScalloped.blp]]) 

-- -----
--   FONT
-- -----

-- -----
--   SOUND
-- -----
LSM:Register("sound", "AirHorn", [[Interface\Addons\SharedMedia_MyMedia\sound\AirHorn.ogg]]) 
LSM:Register("sound", "Alert1", [[Interface\Addons\SharedMedia_MyMedia\sound\Alert1.ogg]]) 
LSM:Register("sound", "Alert2", [[Interface\Addons\SharedMedia_MyMedia\sound\Alert2.ogg]]) 
LSM:Register("sound", "Alert3", [[Interface\Addons\SharedMedia_MyMedia\sound\Alert3.ogg]]) 
LSM:Register("sound", "Bam", [[Interface\Addons\SharedMedia_MyMedia\sound\Bam.ogg]]) 
LSM:Register("sound", "Beware", [[Interface\Addons\SharedMedia_MyMedia\sound\Beware.ogg]]) 
LSM:Register("sound", "Dominating", [[Interface\Addons\SharedMedia_MyMedia\sound\Dominating.ogg]]) 
LSM:Register("sound", "DontDie", [[Interface\Addons\SharedMedia_MyMedia\sound\DontDie.ogg]]) 
LSM:Register("sound", "GodLike", [[Interface\Addons\SharedMedia_MyMedia\sound\GodLike.ogg]]) 
LSM:Register("sound", "HeadShot", [[Interface\Addons\SharedMedia_MyMedia\sound\HeadShot.ogg]]) 
LSM:Register("sound", "Incredible", [[Interface\Addons\SharedMedia_MyMedia\sound\Incredible.ogg]]) 
LSM:Register("sound", "KillingSpree", [[Interface\Addons\SharedMedia_MyMedia\sound\KillingSpree.ogg]]) 
LSM:Register("sound", "LudicrousKill", [[Interface\Addons\SharedMedia_MyMedia\sound\LudicrousKill.ogg]]) 
LSM:Register("sound", "MarioDie", [[Interface\Addons\SharedMedia_MyMedia\sound\MarioDie.ogg]]) 
LSM:Register("sound", "MonsterKill", [[Interface\Addons\SharedMedia_MyMedia\sound\MonsterKill.ogg]]) 
LSM:Register("sound", "MultiKill", [[Interface\Addons\SharedMedia_MyMedia\sound\MultiKill.ogg]]) 
LSM:Register("sound", "Rampage", [[Interface\Addons\SharedMedia_MyMedia\sound\Rampage.ogg]]) 
LSM:Register("sound", "UltraKill", [[Interface\Addons\SharedMedia_MyMedia\sound\UltraKill.ogg]]) 
LSM:Register("sound", "Unstoppable", [[Interface\Addons\SharedMedia_MyMedia\sound\Unstoppable.ogg]]) 
LSM:Register("sound", "YouSuck", [[Interface\Addons\SharedMedia_MyMedia\sound\YouSuck.ogg]]) 

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "Aluminium", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Aluminium.tga]]) 
LSM:Register("statusbar", "Armory", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Armory.tga]]) 
LSM:Register("statusbar", "BantoBar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BantoBar.tga]]) 
LSM:Register("statusbar", "Bars", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bars.tga]]) 
LSM:Register("statusbar", "Bezo-dark1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bezo-dark1.blp]]) 
LSM:Register("statusbar", "Bezo-dark2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bezo-dark2.blp]]) 
LSM:Register("statusbar", "Bezo", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bezo.blp]]) 
LSM:Register("statusbar", "Blinkii", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Blinkii.tga]]) 
LSM:Register("statusbar", "BlizzardCast", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardCast.tga]]) 
LSM:Register("statusbar", "BlizzardCastBackground", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardCastBackground.tga]]) 
LSM:Register("statusbar", "BlizzardCastBgRound", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardCastBgRound.tga]]) 
LSM:Register("statusbar", "BlizzardCastLite", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardCastLite.tga]]) 
LSM:Register("statusbar", "BlizzardCastRound", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardCastRound.tga]]) 
LSM:Register("statusbar", "BlizzardCastUninterruptableRound", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardCastUninterruptableRound.tga]]) 
LSM:Register("statusbar", "BlizzardChannelRound", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardChannelRound.tga]]) 
LSM:Register("statusbar", "BlizzardContainerFrame", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardContainerFrame.tga]]) 
LSM:Register("statusbar", "BlizzardDF_bar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardDF_bar.tga]]) 
LSM:Register("statusbar", "BlizzardObjectiveTracker", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardObjectiveTracker.tga]]) 
LSM:Register("statusbar", "BlizzardObjectiveTrackerlow", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardObjectiveTrackerlow.tga]]) 
LSM:Register("statusbar", "BlizzardOnePixelBackground", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardOnePixelBackground.tga]]) 
LSM:Register("statusbar", "BlizzardOnePixelBackground2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardOnePixelBackground2.tga]]) 
LSM:Register("statusbar", "BlizzardOnePixelBar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardOnePixelBar.tga]]) 
LSM:Register("statusbar", "BlizzardOnePixelbar2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BlizzardOnePixelbar2.tga]]) 
LSM:Register("statusbar", "BuiOnePixel", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BuiOnePixel.tga]]) 
LSM:Register("statusbar", "Bumps", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bumps.tga]]) 
LSM:Register("statusbar", "Button", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Button.tga]]) 
LSM:Register("statusbar", "Charcoal", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Charcoal.tga]]) 
LSM:Register("statusbar", "Cilo", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Cilo.tga]]) 
LSM:Register("statusbar", "Cloud", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Cloud.tga]]) 
LSM:Register("statusbar", "Combo", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Combo.tga]]) 
LSM:Register("statusbar", "Comet", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Comet.tga]]) 
LSM:Register("statusbar", "Dabs", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Dabs.tga]]) 
LSM:Register("statusbar", "DarkBottom", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DarkBottom.tga]]) 
LSM:Register("statusbar", "Diagonal", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Diagonal.tga]]) 
LSM:Register("statusbar", "Empty", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Empty.tga]]) 
LSM:Register("statusbar", "Falumn", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Falumn.tga]]) 
LSM:Register("statusbar", "Ferous1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous1.tga]]) 
LSM:Register("statusbar", "Ferous10", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous10.tga]]) 
LSM:Register("statusbar", "Ferous11", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous11.tga]]) 
LSM:Register("statusbar", "Ferous12", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous12.tga]]) 
LSM:Register("statusbar", "Ferous13", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous13.tga]]) 
LSM:Register("statusbar", "Ferous14", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous14.tga]]) 
LSM:Register("statusbar", "Ferous15", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous15.tga]]) 
LSM:Register("statusbar", "Ferous16", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous16.tga]]) 
LSM:Register("statusbar", "Ferous17", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous17.tga]]) 
LSM:Register("statusbar", "Ferous18", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous18.tga]]) 
LSM:Register("statusbar", "Ferous19", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous19.tga]]) 
LSM:Register("statusbar", "Ferous2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous2.tga]]) 
LSM:Register("statusbar", "Ferous20", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous20.tga]]) 
LSM:Register("statusbar", "Ferous21", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous21.tga]]) 
LSM:Register("statusbar", "Ferous22", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous22.tga]]) 
LSM:Register("statusbar", "Ferous23", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous23.tga]]) 
LSM:Register("statusbar", "Ferous24", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous24.tga]]) 
LSM:Register("statusbar", "Ferous25", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous25.tga]]) 
LSM:Register("statusbar", "Ferous26", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous26.tga]]) 
LSM:Register("statusbar", "Ferous27", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous27.tga]]) 
LSM:Register("statusbar", "Ferous28", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous28.tga]]) 
LSM:Register("statusbar", "Ferous29", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous29.tga]]) 
LSM:Register("statusbar", "Ferous3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous3.tga]]) 
LSM:Register("statusbar", "Ferous30", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous30.tga]]) 
LSM:Register("statusbar", "Ferous31", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous31.tga]]) 
LSM:Register("statusbar", "Ferous32", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous32.tga]]) 
LSM:Register("statusbar", "Ferous33", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous33.tga]]) 
LSM:Register("statusbar", "Ferous34", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous34.tga]]) 
LSM:Register("statusbar", "Ferous35", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous35.tga]]) 
LSM:Register("statusbar", "Ferous36", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous36.tga]]) 
LSM:Register("statusbar", "Ferous37", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous37.tga]]) 
LSM:Register("statusbar", "Ferous4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous4.tga]]) 
LSM:Register("statusbar", "Ferous5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous5.tga]]) 
LSM:Register("statusbar", "Ferous6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous6.tga]]) 
LSM:Register("statusbar", "Ferous7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous7.tga]]) 
LSM:Register("statusbar", "Ferous8", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous8.tga]]) 
LSM:Register("statusbar", "Ferous9", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous9.tga]]) 
LSM:Register("statusbar", "Fifths", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Fifths.tga]]) 
LSM:Register("statusbar", "Flat", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Flat.tga]]) 
LSM:Register("statusbar", "Fourths", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Fourths.tga]]) 
LSM:Register("statusbar", "Frost", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Frost.tga]]) 
LSM:Register("statusbar", "Glamour", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour.tga]]) 
LSM:Register("statusbar", "Glamour2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour2.tga]]) 
LSM:Register("statusbar", "Glamour3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour3.tga]]) 
LSM:Register("statusbar", "Glamour4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour4.tga]]) 
LSM:Register("statusbar", "Glamour5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour5.tga]]) 
LSM:Register("statusbar", "Glamour6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour6.tga]]) 
LSM:Register("statusbar", "Glamour7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour7.tga]]) 
LSM:Register("statusbar", "Glass", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glass.tga]]) 
LSM:Register("statusbar", "Glaze", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glaze.tga]]) 
LSM:Register("statusbar", "Glaze2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glaze2.tga]]) 
LSM:Register("statusbar", "Gloss", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Gloss.tga]]) 
LSM:Register("statusbar", "Graphite", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Graphite.tga]]) 
LSM:Register("statusbar", "Grid", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Grid.tga]]) 
LSM:Register("statusbar", "Hatched", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Hatched.tga]]) 
LSM:Register("statusbar", "Healbot", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Healbot.tga]]) 
LSM:Register("statusbar", "LiteStep", [[Interface\Addons\SharedMedia_MyMedia\statusbar\LiteStep.tga]]) 
LSM:Register("statusbar", "LiteStepLite", [[Interface\Addons\SharedMedia_MyMedia\statusbar\LiteStepLite.tga]]) 
LSM:Register("statusbar", "Lyfe", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Lyfe.tga]]) 
LSM:Register("statusbar", "Melli", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Melli.tga]]) 
LSM:Register("statusbar", "MelliDark", [[Interface\Addons\SharedMedia_MyMedia\statusbar\MelliDark.tga]]) 
LSM:Register("statusbar", "MelliDarkRough", [[Interface\Addons\SharedMedia_MyMedia\statusbar\MelliDarkRough.tga]]) 
LSM:Register("statusbar", "Minimalist", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Minimalist.tga]]) 
LSM:Register("statusbar", "Norm", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Norm.tga]]) 
LSM:Register("statusbar", "Otravi", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Otravi.tga]]) 
LSM:Register("statusbar", "Outline", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Outline.tga]]) 
LSM:Register("statusbar", "Perl", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Perl.tga]]) 
LSM:Register("statusbar", "Perl2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Perl2.tga]]) 
LSM:Register("statusbar", "Pill", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Pill.tga]]) 
LSM:Register("statusbar", "Raeli1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli1.tga]]) 
LSM:Register("statusbar", "Raeli2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli2.tga]]) 
LSM:Register("statusbar", "Raeli3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli3.tga]]) 
LSM:Register("statusbar", "Raeli4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli4.tga]]) 
LSM:Register("statusbar", "Raeli5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli5.tga]]) 
LSM:Register("statusbar", "Raeli6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli6.tga]]) 
LSM:Register("statusbar", "Rain", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Rain.tga]]) 
LSM:Register("statusbar", "Rocks", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Rocks.tga]]) 
LSM:Register("statusbar", "Round", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Round.tga]]) 
LSM:Register("statusbar", "Ruben", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ruben.tga]]) 
LSM:Register("statusbar", "Runes", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Runes.tga]]) 
LSM:Register("statusbar", "Skewed", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Skewed.tga]]) 
LSM:Register("statusbar", "SmokObjectiveTracker", [[Interface\Addons\SharedMedia_MyMedia\statusbar\SmokObjectiveTracker.tga]]) 
LSM:Register("statusbar", "SmokOnePixelBackground", [[Interface\Addons\SharedMedia_MyMedia\statusbar\SmokOnePixelBackground.tga]]) 
LSM:Register("statusbar", "SmokOnePixelbar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\SmokOnePixelbar.tga]]) 
LSM:Register("statusbar", "Smooth", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Smooth.tga]]) 
LSM:Register("statusbar", "Smoothv2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Smoothv2.tga]]) 
LSM:Register("statusbar", "Smudge", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Smudge.tga]]) 
LSM:Register("statusbar", "spec_icons_normal_alpha2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\spec_icons_normal_alpha2.tga]]) 
LSM:Register("statusbar", "spec_icons_normal_alpha3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\spec_icons_normal_alpha3.tga]]) 
LSM:Register("statusbar", "Steel", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Steel.tga]]) 
LSM:Register("statusbar", "Striped", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Striped.tga]]) 
LSM:Register("statusbar", "ToxiUI-clean", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-clean.tga]]) 
LSM:Register("statusbar", "ToxiUI-dark", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-dark.tga]]) 
LSM:Register("statusbar", "ToxiUI-g1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-g1.tga]]) 
LSM:Register("statusbar", "ToxiUI-g2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-g2.tga]]) 
LSM:Register("statusbar", "ToxiUI-grad", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-grad.tga]]) 
LSM:Register("statusbar", "ToxiUI-half", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-half.tga]]) 
LSM:Register("statusbar", "Tube", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Tube.tga]]) 
LSM:Register("statusbar", "TX-WorldState-Score", [[Interface\Addons\SharedMedia_MyMedia\statusbar\TX-WorldState-Score.blp]]) 
LSM:Register("statusbar", "Water", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Water.tga]]) 
LSM:Register("statusbar", "Wglass", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wglass.tga]]) 
LSM:Register("statusbar", "Wisps", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wisps.tga]]) 
LSM:Register("statusbar", "Xeon", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Xeon.tga]]) 
